<?php

/**
 * ActivitysTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitysTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitysTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activitys');
    }
}