<?php

/**
 * AdministradorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdministradorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdministradorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Administrador');
    }
}