<?php

/**
 * CategoriasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categorias');
    }
}