<?php

/**
 * DocumentationCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentationCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentationCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentationCategory');
    }
}