<?php

/**
 * FilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Files');
    }
}