<?php

/**
 * FilesDefaultTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilesDefaultTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilesDefaultTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FilesDefault');
    }
}