<?php

/**
 * HeadersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HeadersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HeadersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Headers');
    }
}