<?php

/**
 * ModulesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModulesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModulesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Modules');
    }
}