<?php

/**
 * NoticiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoticiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Noticias');
    }
}