<?php

/**
 * NoticiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoticiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Noticia');
    }
}