<?php

/**
 * PageDynamicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageDynamicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageDynamicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PageDynamic');
    }
}