<?php

/**
 * PagedynamicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagedynamicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagedynamicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pagedynamic');
    }
}