<?php

/**
 * PalcosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PalcosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PalcosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Palcos');
    }
}