<?php

/**
 * PanelPrincipalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PanelPrincipalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PanelPrincipalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PanelPrincipal');
    }
}