<?php

/**
 * PermisosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermisosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PermisosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Permisos');
    }
}