<?php

/**
 * PlataformaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlataformaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlataformaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plataforma');
    }
}