<?php

/**
 * ProgramaEspecialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramaEspecialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramaEspecialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramaEspecial');
    }
}