<?php

/**
 * PublicidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Publicidad');
    }
}