<?php

/**
 * PublicacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Publicaciones');
    }
}