<?php

/**
 * SaludoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaludoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaludoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Saludo');
    }
}