<?php

/**
 * UltimoAudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UltimoAudioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UltimoAudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UltimoAudio');
    }
}