<?php

/**
 * UltimaHoraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UltimaHoraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UltimaHoraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UltimaHora');
    }
}