<?php

/**
 * UltimosProgramasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UltimosProgramasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UltimosProgramasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UltimosProgramas');
    }
}