<?php

/**
 * UsersAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersAccess');
    }
}