<?php

/**
 * UsuarioBlogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioBlogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioBlogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioBlog');
    }
}